# Generated by Django 4.2 on 2023-04-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmed',
            new_name='is_confirmed',
        ),
    ]
